// DesignIntelligence.jsx — shows the Claude-generated palette, font pairing,
// and reference analysis (the three design skills) as a row of cards.

import { useGoogleFont } from "../useGoogleFont.js";

const CLAUDE_LABEL = "Generated by Claude ✦";

export default function DesignIntelligence({ skills }) {
  const palette = skills?.palette;
  const fonts = skills?.fonts;
  const reference = skills?.reference;

  // Load the suggested fonts so the font card can render in the real faces.
  useGoogleFont(fonts?.google_fonts_url);

  return (
    <section className="rounded-xl border border-slate-200 bg-white p-5">
      <div className="flex items-center justify-between mb-4">
        <h3 className="font-semibold text-slate-800">Design Intelligence</h3>
        <span className="text-xs text-violet-500 font-medium">{CLAUDE_LABEL}</span>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <PaletteCard palette={palette} />
        <FontCard fonts={fonts} />
        <ReferenceCard reference={reference} />
      </div>
    </section>
  );
}

function CardShell({ title, children }) {
  return (
    <div className="rounded-lg border border-slate-200 bg-slate-50/60 p-4 flex flex-col">
      <div className="flex items-center justify-between mb-3">
        <h4 className="text-sm font-semibold text-slate-700">{title}</h4>
        <span className="text-[10px] text-violet-400 font-medium">
          {CLAUDE_LABEL}
        </span>
      </div>
      {children}
    </div>
  );
}

function PaletteCard({ palette }) {
  if (!palette || palette._failed) {
    return (
      <CardShell title="Color Palette">
        <p className="text-xs text-slate-400">
          {palette?._error ? `Failed: ${palette._error}` : "Not available."}
        </p>
      </CardShell>
    );
  }

  const swatches = [
    ["Primary", palette.primary],
    ["Accent", palette.accent],
    ["Background", palette.background],
    ["Surface", palette.surface],
    ["Text", palette.text],
  ];

  return (
    <CardShell title="Color Palette">
      <div className="space-y-2">
        {swatches.map(([label, hex]) => (
          <div key={label} className="flex items-center gap-2">
            <span
              className="w-6 h-6 rounded-md border border-slate-200 shadow-sm shrink-0"
              style={{ backgroundColor: hex || "transparent" }}
            />
            <div className="min-w-0">
              <p className="text-xs font-medium text-slate-700 leading-tight">
                {label}
              </p>
              <p className="text-[11px] text-slate-400 leading-tight">
                {hex || "—"}
              </p>
            </div>
          </div>
        ))}
      </div>
      {palette.rationale && (
        <p className="text-xs italic text-slate-500 mt-3">{palette.rationale}</p>
      )}
    </CardShell>
  );
}

function FontCard({ fonts }) {
  if (!fonts || fonts._failed) {
    return (
      <CardShell title="Typography">
        <p className="text-xs text-slate-400">
          {fonts?._error ? `Failed: ${fonts._error}` : "Not available."}
        </p>
      </CardShell>
    );
  }

  return (
    <CardShell title="Typography">
      <div className="space-y-3">
        <div>
          <p className="text-[11px] uppercase tracking-wide text-slate-400">
            Heading
          </p>
          <p
            className="text-xl text-slate-800 leading-tight"
            style={{
              fontFamily: fonts.heading_font
                ? `'${fonts.heading_font}', serif`
                : undefined,
              fontWeight: fonts.heading_weight || 700,
            }}
          >
            {fonts.heading_font || "—"}
          </p>
        </div>
        <div>
          <p className="text-[11px] uppercase tracking-wide text-slate-400">
            Body
          </p>
          <p
            className="text-base text-slate-700 leading-snug"
            style={{
              fontFamily: fonts.body_font
                ? `'${fonts.body_font}', sans-serif`
                : undefined,
              fontWeight: fonts.body_weight || 400,
            }}
          >
            {fonts.body_font || "—"} — The quick brown fox jumps over the lazy dog.
          </p>
        </div>
        <div className="flex gap-2 flex-wrap text-[11px] text-slate-500">
          {fonts.heading_size_desktop && (
            <span className="px-2 py-0.5 rounded bg-white border border-slate-200">
              H1 {fonts.heading_size_desktop}
            </span>
          )}
          {fonts.body_size_desktop && (
            <span className="px-2 py-0.5 rounded bg-white border border-slate-200">
              Body {fonts.body_size_desktop}
            </span>
          )}
        </div>
      </div>
      {fonts.rationale && (
        <p className="text-xs italic text-slate-500 mt-3">{fonts.rationale}</p>
      )}
    </CardShell>
  );
}

function ReferenceCard({ reference }) {
  if (!reference || reference._failed) {
    return (
      <CardShell title="Reference Analysis">
        <p className="text-xs text-slate-400">
          {reference?._error
            ? `Failed: ${reference._error}`
            : "Not available."}
        </p>
      </CardShell>
    );
  }

  if (reference._skipped) {
    return (
      <CardShell title="Reference Analysis">
        <p className="text-xs text-slate-400">
          No reference was provided by the client.
        </p>
      </CardShell>
    );
  }

  const principles = reference.layout_principles || [];
  const trust = reference.trust_elements || [];

  return (
    <CardShell title="Reference Analysis">
      {reference.what_to_borrow && (
        <div className="rounded-md bg-emerald-50 border border-emerald-200 px-3 py-2 mb-3">
          <p className="text-[11px] font-semibold text-emerald-700 mb-0.5">
            Borrow this
          </p>
          <p className="text-xs text-emerald-800">{reference.what_to_borrow}</p>
        </div>
      )}

      {principles.length > 0 && (
        <div className="mb-3">
          <p className="text-[11px] uppercase tracking-wide text-slate-400 mb-1">
            Layout principles
          </p>
          <ul className="space-y-1">
            {principles.map((p, i) => (
              <li key={i} className="text-xs text-slate-600 flex gap-1.5">
                <span className="text-slate-300">•</span>
                <span>{p}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {trust.length > 0 && (
        <div>
          <p className="text-[11px] uppercase tracking-wide text-slate-400 mb-1">
            Trust elements
          </p>
          <div className="flex flex-wrap gap-1">
            {trust.map((t, i) => (
              <span
                key={i}
                className="px-2 py-0.5 rounded-full bg-white border border-slate-200 text-[11px] text-slate-600"
              >
                {t}
              </span>
            ))}
          </div>
        </div>
      )}
    </CardShell>
  );
}
