import { useEffect, useState } from "react";
import { api } from "../api.js";
import { useGoogleFont } from "../useGoogleFont.js";

// WireframePreview.jsx — low-fidelity rendering of a spec's pages and sections,
// tinted with the real design tokens generated by the design skills.
export default function WireframePreview({ preselect, onBack }) {
  const [specs, setSpecs] = useState([]);
  const [selected, setSelected] = useState(preselect || "");
  const [spec, setSpec] = useState(null);
  const [activePage, setActivePage] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    api
      .getSpecs()
      .then((list) => {
        setSpecs(list);
        if (!selected && list.length > 0) setSelected(list[0].filename);
      })
      .catch((err) => setError(err.message));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!selected) return;
    setLoading(true);
    setError(null);
    api
      .getSpec(selected)
      .then((data) => {
        setSpec(data);
        setActivePage(0);
      })
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, [selected]);

  // Real design tokens (with sensible fallbacks to the original neutral look).
  const t = spec?.design_tokens || {};
  const brand = {
    primary: t.primary_color || "#2d6a4f",
    accent: t.accent_color || "#52b788",
    background: t.background_color || "#ffffff",
    surface: t.surface_color || "#f8fafc",
    text: t.text_color || "#0f172a",
    heading: t.font_heading,
    body: t.font_body,
    fontsUrl: t.google_fonts_url,
  };

  // Load the suggested Google Fonts so the preview renders in the real faces.
  useGoogleFont(brand.fontsUrl);

  if (specs.length === 0 && !error) {
    return (
      <div className="max-w-2xl mx-auto text-center mt-20 text-slate-500">
        <h2 className="text-2xl font-bold text-slate-900 mb-2">
          Wireframe Preview
        </h2>
        <p>No specs generated yet. Generate one from the Responses tab.</p>
      </div>
    );
  }

  const pages = spec?.pages || [];
  const page = pages[activePage];
  const slug =
    selected.replace(/^\d+-/, "").replace(/\.json$/, "") || "preview";
  const client = spec?.client || {};

  // CSS variables drive the brand tint for all nested section pieces.
  const brandVars = {
    "--wf-primary": brand.primary,
    "--wf-accent": brand.accent,
    "--wf-surface": brand.surface,
    "--wf-text": brand.text,
    "--wf-heading": brand.heading
      ? `'${brand.heading}', ui-serif, Georgia, serif`
      : "inherit",
    backgroundColor: brand.background,
    fontFamily: brand.body
      ? `'${brand.body}', ui-sans-serif, system-ui, sans-serif`
      : undefined,
  };

  return (
    <div className="max-w-5xl mx-auto">
      <button
        onClick={onBack}
        className="mb-4 inline-flex items-center gap-1 text-sm font-medium text-slate-600 hover:text-slate-900"
      >
        ← Back to Spec
      </button>

      <header className="mb-5 flex items-end justify-between gap-4 flex-wrap">
        <h2 className="text-2xl font-bold text-slate-900">Wireframe Preview</h2>
        <select
          value={selected}
          onChange={(e) => setSelected(e.target.value)}
          className="px-3 py-2 rounded-lg border border-slate-300 bg-white text-sm"
        >
          {specs.map((s) => (
            <option key={s.filename} value={s.filename}>
              {s.business_name}
            </option>
          ))}
        </select>
      </header>

      {error && (
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 mb-4">
          {error}
        </div>
      )}

      {loading && <p className="text-slate-400">Loading preview…</p>}

      {spec && !loading && (
        <div className="rounded-xl overflow-hidden border border-slate-300 shadow-lg bg-white">
          {/* Fake browser chrome */}
          <div className="flex items-center gap-3 bg-slate-200 px-4 py-2.5 border-b border-slate-300">
            <div className="flex gap-1.5">
              <span className="w-3 h-3 rounded-full bg-red-400" />
              <span className="w-3 h-3 rounded-full bg-yellow-400" />
              <span className="w-3 h-3 rounded-full bg-green-400" />
            </div>
            <div className="flex-1 bg-white rounded-md px-3 py-1 text-xs text-slate-400 truncate">
              https://{slug}.com
            </div>
          </div>

          {/* Page tabs */}
          {pages.length > 1 && (
            <div className="flex gap-1 bg-slate-100 px-3 pt-2 border-b border-slate-200">
              {pages.map((p, i) => (
                <button
                  key={i}
                  onClick={() => setActivePage(i)}
                  className={
                    "px-3 py-1.5 text-xs font-medium rounded-t-md " +
                    (i === activePage
                      ? "bg-white text-slate-800 border border-b-0 border-slate-200"
                      : "text-slate-500 hover:text-slate-700")
                  }
                >
                  {p.name}
                </button>
              ))}
            </div>
          )}

          {/* Sections — brand variables applied here flow to all children */}
          <div className="p-4 space-y-4" style={brandVars}>
            {(page?.sections || []).map((section, si) => (
              <SectionFrame key={si} section={section} client={client} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// --- section frame wrapper -------------------------------------------------

function SectionFrame({ section, client }) {
  const { type, notes } = section;
  return (
    <div
      className="relative rounded-lg border-2 border-dashed border-slate-300 p-4"
      style={{ backgroundColor: "var(--wf-surface)" }}
    >
      <span
        className="absolute top-2 right-2 px-2 py-0.5 rounded text-[10px] font-semibold text-white z-10"
        style={{ backgroundColor: "var(--wf-primary)" }}
      >
        {type}
      </span>

      <SectionBody section={section} client={client} />

      {notes && (
        <p className="text-xs italic text-slate-400 mt-3 pt-2 border-t border-slate-100">
          {notes}
        </p>
      )}
    </div>
  );
}

// --- low-fi building blocks ------------------------------------------------

function Bar({ w = "100%", h = 12, className = "" }) {
  return (
    <div
      className={"rounded bg-slate-200 " + className}
      style={{ width: w, height: h }}
    />
  );
}

function Box({ h = 120, className = "", label }) {
  return (
    <div
      className={
        "rounded bg-slate-100 border border-slate-200 flex items-center justify-center text-xs text-slate-400 " +
        className
      }
      style={{ height: h }}
    >
      {label}
    </div>
  );
}

function Circle({ size = 40 }) {
  return (
    <div
      className="rounded-full bg-slate-200"
      style={{ width: size, height: size }}
    />
  );
}

// Branded button: filled uses the primary color, outline uses the accent.
function ButtonOutline({ filled = false, w = 110 }) {
  return (
    <div
      className="rounded-md h-9"
      style={
        filled
          ? { width: w, backgroundColor: "var(--wf-primary)" }
          : {
              width: w,
              border: "2px solid var(--wf-accent)",
              backgroundColor: "transparent",
            }
      }
    />
  );
}

// Branded section title — real text in the heading font + a primary accent rule.
function SectionTitle({ text }) {
  return (
    <div className="flex flex-col items-center mb-5">
      <span
        className="text-xl font-bold tracking-tight"
        style={{ fontFamily: "var(--wf-heading)", color: "var(--wf-text)" }}
      >
        {text}
      </span>
      <span
        className="mt-1.5 h-1 w-12 rounded"
        style={{ backgroundColor: "var(--wf-primary)" }}
      />
    </div>
  );
}

// --- per-type renderers ----------------------------------------------------

function SectionBody({ section, client }) {
  const { type, variant } = section;
  switch (type) {
    case "nav":
      return <NavSection />;
    case "hero":
      return <HeroSection variant={variant} client={client} />;
    case "services":
    case "features":
      return <ServicesSection />;
    case "gallery":
      return <GallerySection />;
    case "about":
      return <AboutSection />;
    case "testimonials":
      return <TestimonialsSection />;
    case "contact":
      return <ContactSection />;
    case "cta":
      return <CtaSection />;
    case "pricing":
      return <PricingSection />;
    case "faq":
      return <FaqSection />;
    case "footer":
      return <FooterSection />;
    default:
      return <GenericSection type={type} />;
  }
}

function NavSection() {
  return (
    <div className="flex items-center justify-between pr-16">
      <Box h={28} className="w-24" label="logo" />
      <div className="flex items-center gap-4">
        {[0, 1, 2].map((i) => (
          <Bar key={i} w={48} h={10} />
        ))}
        {/* Phone/CTA pill in the brand color */}
        <span
          className="h-7 w-20 rounded-md"
          style={{ backgroundColor: "var(--wf-primary)" }}
        />
      </div>
    </div>
  );
}

function HeroSection({ variant, client }) {
  const headline = client?.business_name || null;
  const subtitle = client?.tagline || null;

  const Headline = () =>
    headline ? (
      <h1
        className="text-3xl font-bold tracking-tight"
        style={{ fontFamily: "var(--wf-heading)", color: "var(--wf-text)" }}
      >
        {headline}
      </h1>
    ) : (
      <Bar w="70%" h={32} />
    );

  const Subtitle = () =>
    subtitle ? (
      <p className="text-sm" style={{ color: "var(--wf-text)", opacity: 0.7 }}>
        {subtitle}
      </p>
    ) : (
      <>
        <Bar w="45%" h={14} />
        <Bar w="40%" h={14} />
      </>
    );

  if (variant === "split") {
    return (
      <div className="grid grid-cols-2 gap-6 items-center" style={{ minHeight: 300 }}>
        <div className="space-y-3">
          <Headline />
          <Subtitle />
          <div className="flex gap-3 pt-2">
            <ButtonOutline filled />
            <ButtonOutline />
          </div>
        </div>
        <Box h={240} label="hero image" />
      </div>
    );
  }
  return (
    <div
      className="flex flex-col items-center justify-center text-center gap-3"
      style={{ minHeight: 300 }}
    >
      <Headline />
      <Subtitle />
      <div className="flex gap-3 pt-3">
        <ButtonOutline filled />
        <ButtonOutline />
      </div>
    </div>
  );
}

function ServicesSection() {
  return (
    <div className="pr-12">
      <SectionTitle text="Our Services" />
      <div className="grid grid-cols-3 gap-4">
        {[0, 1, 2].map((i) => (
          <div
            key={i}
            className="rounded-lg border border-slate-200 p-4 flex flex-col items-center gap-2 bg-white"
          >
            <div
              className="rounded-full"
              style={{ width: 44, height: 44, backgroundColor: "var(--wf-accent)" }}
            />
            <Bar w="70%" h={12} />
            <Bar w="90%" h={8} />
            <Bar w="85%" h={8} />
            <Bar w="80%" h={8} />
          </div>
        ))}
      </div>
    </div>
  );
}

function GallerySection() {
  return (
    <div className="pr-12">
      <SectionTitle text="Gallery" />
      <div className="grid grid-cols-3 gap-3">
        {Array.from({ length: 6 }).map((_, i) => (
          <Box key={i} h={90} label="photo" />
        ))}
      </div>
    </div>
  );
}

function AboutSection() {
  return (
    <div className="grid grid-cols-2 gap-6 items-center pr-12">
      <div className="space-y-2">
        {[0, 1, 2, 3, 4].map((i) => (
          <Bar key={i} w={`${95 - i * 8}%`} h={12} />
        ))}
      </div>
      <Box h={180} label="image" />
    </div>
  );
}

function TestimonialsSection() {
  return (
    <div className="pr-12">
      <SectionTitle text="What Our Clients Say" />
      <div className="grid grid-cols-2 gap-4">
        {[0, 1].map((i) => (
          <div
            key={i}
            className="rounded-lg border border-slate-200 p-4 space-y-2 bg-white"
          >
            <Bar w="100%" h={10} />
            <Bar w="95%" h={10} />
            <Bar w="80%" h={10} />
            <div className="flex items-center gap-3 pt-2">
              <div
                className="rounded-full"
                style={{ width: 36, height: 36, backgroundColor: "var(--wf-accent)" }}
              />
              <Bar w={90} h={10} />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function ContactSection() {
  return (
    <div className="pr-12">
      <SectionTitle text="Get in Touch" />
      <div className="max-w-md mx-auto space-y-3">
        {["Name", "Email", "Phone"].map((label) => (
          <div
            key={label}
            className="h-10 rounded-md border-2 border-slate-200 flex items-center px-3 text-xs text-slate-400 bg-white"
          >
            {label}
          </div>
        ))}
        <div className="h-24 rounded-md border-2 border-slate-200 flex items-start p-3 text-xs text-slate-400 bg-white">
          Message
        </div>
        <div className="flex justify-center pt-1">
          <ButtonOutline filled w={140} />
        </div>
      </div>
    </div>
  );
}

function CtaSection() {
  return (
    <div
      className="rounded-lg py-10 flex flex-col items-center gap-4"
      style={{ backgroundColor: "var(--wf-primary)" }}
    >
      <Bar w="50%" h={24} className="bg-white/80" />
      <div className="h-10 w-36 rounded-md bg-white" />
    </div>
  );
}

function PricingSection() {
  return (
    <div className="pr-12">
      <SectionTitle text="Pricing" />
      <div className="grid grid-cols-3 gap-4">
        {[0, 1, 2].map((i) => (
          <div
            key={i}
            className="rounded-lg border border-slate-200 p-4 flex flex-col items-center gap-2 bg-white"
          >
            <Bar w="60%" h={12} />
            <Bar w="45%" h={22} />
            {[0, 1, 2, 3].map((k) => (
              <Bar key={k} w="80%" h={8} />
            ))}
            <div className="pt-2">
              <ButtonOutline filled w={100} />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function FaqSection() {
  return (
    <div className="pr-12">
      <SectionTitle text="Frequently Asked Questions" />
      <div className="max-w-2xl mx-auto space-y-2">
        {Array.from({ length: 5 }).map((_, i) => (
          <div
            key={i}
            className="flex items-center justify-between rounded-md border border-slate-200 px-4 py-3 bg-white"
          >
            <Bar w="60%" h={12} />
            <span className="text-slate-400 text-lg leading-none">⌄</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function FooterSection() {
  return (
    <div
      className="rounded-lg p-6"
      style={{ backgroundColor: "var(--wf-text)" }}
    >
      <div className="grid grid-cols-3 gap-6">
        {[0, 1, 2].map((col) => (
          <div key={col} className="space-y-2">
            {[0, 1, 2].map((i) => (
              <Bar
                key={i}
                w={`${70 - i * 10}%`}
                h={8}
                className="bg-white/30"
              />
            ))}
          </div>
        ))}
      </div>
      <div className="mt-6 pt-4 border-t border-white/20 flex justify-center">
        <Bar w="40%" h={8} className="bg-white/30" />
      </div>
    </div>
  );
}

function GenericSection({ type }) {
  return (
    <div className="py-6 flex flex-col items-center gap-3">
      <Bar w="40%" h={18} />
      <Bar w="80%" h={10} />
      <Bar w="75%" h={10} />
      <p className="text-xs text-slate-400 mt-1">section: {type}</p>
    </div>
  );
}
